# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
dist: trusty

python:
  - "3.5"

services:
  - docker

before_install:
  - docker pull alpine
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - sudo pip3 install -U numpy docker
