# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
dist: trusty

r:
  - oldrel
  - release
  - devel

env:
  global:
    - NOT_CRAN=true
  matrix:
    - PYTHON=2 PIP="pip" RETICULATE_PYTHON="/usr/bin/python"
    - PYTHON=3 PIP="pip3" RETICULATE_PYTHON="/usr/bin/python3"
    - PYTHON=3 PIP="pip3" RETICULATE_PYTHON="/usr/bin/python3"
    - PYTHON=3 PIP="pip3" RETICULATE_PYTHON="/usr/bin/python3"

services:
  - docker

before_install:
  - docker pull alpine
  - test "x$PYTHON" = "x2" && sudo apt-get -y install python-pip python-numpy python-dev
  - test "x$PYTHON" = "x3" && sudo apt-get -y install python3-pip python-dev python3-numpy
  - sudo $PYTHON install -U setuptools
  - sudo $PYTHON install -U docker
