# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
dist: trusty

r:
  - oldrel
  - release
  - devel

python:
  - "3.5"

services:
  - docker

before_install:
  - docker pull alpine
  - sudo apt-get -y install python3-pip python-dev python3-numpy
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U docker
