# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull alpine
  - pip install numpy docker
