# DO NOT CHANGE the "init" and "install" sections below

version: 1.0.{build}
image: Visual Studio 2017

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - "%DOCKER_INSTALL%\\DockerCli.exe -SwitchDaemon"
  - docker pull alpine
  - "%PYTHON%\\python.exe -m pip install setuptools docker"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

environment:
  global:
    DOCKER_HOST: "127.0.0.1:2375"
    _R_CHECK_FORCE_SUGGESTS_: false
    PYTHON: "C:\\Python35"
    DOCKER_INSTALL: "C:\\Program^ Files\\Docker\\Docker\\"

notifications:
  - provider: Email
    to:
      - bhaskarvk@gmail.com
    subject: 'r-appveyor build {{status}}'
    message: "https://ci.appveyor.com/project/bhaskarvk/docker"
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
